name: Run tests
on:
  push:
    paths-ignore:
      - 'docs/**'
      - '.github/ISSUE_TEMPLATE/**'
  pull_request:
    paths-ignore:
      - 'docs/**'
      - '.github/ISSUE_TEMPLATE/**'

env:
  WEBCORD_BUILD: DEVEL

permissions: {}

jobs:
  test:
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        arch: [x64, arm64]
        include:
          - os: ubuntu-latest
            arch: armv7l
          - os: windows-latest
            arch: ia32
    name: ${{ matrix.os }}-${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@master
        with:
          node-version: 16
      - name: Install dependencies
        run: npm install

      - name: Generate artifacts (${{ matrix.arch }})
        run: npm run make -- -a ${{ matrix.arch }}