name: Run tests
on:
  push:
    tags-ignore:
      - '*'
    paths-ignore:
      - 'docs/**'
      - '.github/ISSUE_TEMPLATE/**'
  pull_request:
    paths-ignore:
      - 'docs/**'
      - '.github/ISSUE_TEMPLATE/**'

env:
  WEBCORD_BUILD: DEVEL

permissions: {}

jobs:
  test:
    strategy:
      matrix:
        include:
          - name: Linux
            runner: ubuntu
            arch: x64,arm64,armv7l
          - name: Windows
            runner: windows
            arch: x64,arm64,ia32
          - name: macOS
            runner: macos
            arch: x64,arm64

    name: ${{ matrix.name }} (${{ matrix.arch }})
    runs-on: ${{ matrix.runner }}-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@master
        with:
          node-version: 16
      - name: Install dependencies
        run: npm install

      - name: Generate artifacts (${{ matrix.arch }})
        run: npm run make -- -a ${{ matrix.arch }}

      - uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.name }}
          path: out/*/make/**/*