name: Publish release
on:
  push:
    tags-ignore: ['*beta*']

env:
  WEBCORD_BUILD: RELEASE

permissions:
  contents: write

jobs:
  publish:
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        arch: [x64, arm64]
        include:
          - os: ubuntu-latest
            arch: armv7l
          - os: windows-latest
            arch: ia32
    name: ${{ matrix.os }}-${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@master
        with:
          node-version: 16
      - name: Install dependencies
        run: npm install

      - name: Publish artifacts (${{ matrix.arch}})
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run publish -- -a ${{ matrix.arch }}
